---
permalink: san-migration/concept_target_and_initiator_port_zoning.html 
sidebar: sidebar 
keywords: target, initiator, port, zoning 
summary: FLI移轉需要NetApp儲存設備存取來源儲存LUN。這是透過將來源儲存設備的目標連接埠與目的地儲存設備的啟動器連接埠分區來達成的。 
---
= ONTAP FLI 遷移的目標和啟動器連接埠分區
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FLI 遷移需要NetApp儲存能夠存取外部陣列來源 LUN。這可以透過將來源儲存的目標連接埠與NetApp目標儲存的啟動器連接埠進行分區來實現。

不會修改現有的來源儲存設備對主機區域、並在移轉後停用這些區域。建立主機對目的地儲存區域、以便主機從目的地儲存設備存取移轉的LUN。

使用FLI的標準移轉案例需要四個不同的區域：

* 區域1：來源儲存設備至目的地儲存設備（正式作業架構A）
* 區域2：來源儲存設備至目的地儲存設備（正式作業光纖B）
* 區域3：主機對目的地儲存設備（正式作業架構A）
* 區域4：主機對目的地儲存設備（正式作業架構B）


請遵循以下分區最佳實務做法：

* 請勿將來源儲存目標連接埠與目的地儲存目標連接埠混合在同一個區域中。
* 請勿在同一個區域中混用目的地儲存啟動器連接埠和主機連接埠。
* 請勿在同一個區域中混用目的地儲存目標和啟動器連接埠。
* 每個控制器至少有兩個連接埠的區域、以提供備援。
* NetApp建議使用單一啟動器和單一目標分區。


[NOTE]
====
將來源儲存目標連接埠與目的地儲存啟動器連接埠分區之後、使用儲存陣列show命令即可在目的地儲存設備中看到來源儲存設備。第一次探索儲存陣列時、NetApp控制器可能不會自動顯示陣列。請重設ONTAP 連接了交換器連接埠的交換器連接埠、以修正此問題。

====
使用FLI的標準移轉案例需要四個不同的區域。您應該在每個區域中包含特定的連接埠。

* 區域1：來源儲存設備至目的地儲存設備（正式作業架構A）
+
區域1應包含所有節點上的所有目的地儲存啟動器、以及Fabric A中的所有來源儲存目標連接埠區域成員包括：

+
** –Node1 - ONTAP 0A
** –Node2 - ONTAP 0A
** AMS2100 -- Ctrl0 -- 0A
** AMS2100 -- Ctrl1 -- 1a.


* 區域2：來源儲存設備至目的地儲存設備（正式作業光纖B）
+
區域2應包含所有節點上的所有目的地儲存啟動器連接埠、以及Fabric B中的所有來源儲存目標連接埠區域2成員包括：

+
** –Node1 - ONTAP 0b
** 系統資訊- Node2 - ONTAP 0b
** AMS2100 -- Ctrl0 -- 0e
** AMS2100 -- Ctrl1 -- 1e


* 區域3：主機對目的地儲存設備（正式作業架構A）
+
區域3應包含主機匯流排介面卡（HBA）連接埠1、以及正式作業Fabric A中的目的地控制器連接埠區域3成員包括：

+
** 支援：生命1 ONTAP
** 資訊- ONTAP lif3.
** 主機- HBA0


* 區域4：主機對目的地儲存設備（正式作業架構B）
+
區域4應包含HBA連接埠2和正式作業架構B中的目的地控制器連接埠區域4成員包括：

+
** 資訊- ONTAP lif2.
** 資訊- ONTAP lif4.
** 主機- HBA1



