---
permalink: san-migration/create-lun-import-relationship-offline.html 
sidebar: sidebar 
keywords: ceate, lun import relationship, fli, offline migration 
summary: 在將 LUN 從外部陣列遷移到ONTAP儲存之前，您必須建立 LUN 匯入關係。 LUN導入關係是來源儲存和目標儲存之間為了匯入資料而建立的持久配對。 
---
= 為ONTAP FLI 離線遷移建立 LUN 導入關係
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在將 LUN 從外部陣列遷移到ONTAP儲存系統之前，必須先建立 LUN 導入關係。 LUN導入關係是來源儲存和目標儲存之間為了匯入資料而建立的持久配對。源端點和目標端點都是 LUN。

為外部 LUN 匯入 (FLI) 離線遷移建立 LUN 匯入關係包括在ONTAP中將來源陣列 LUN 識別為外部 LUN、建立和設定目標磁碟區以包含外部 LUN、建立目標 LUN、最後建立匯入關係。

.開始之前
您應該已經完成以下步驟link:prepare-foreign-lun-offline.html["準備外部 LUN 以進行 FLI 離線遷移"] 。



== 步驟 1：在ONTAP中將來源陣列 LUN 標識為外來

在開始 FLI 離線遷移之前，您需要在ONTAP中將來源陣列 LUN 標識為外部 LUN。

.步驟
. 列出從外部陣列對應的來源 LUN；然後驗證磁碟屬性和路徑。
+
[source, cli]
----
storage disk show -array-name <array_name> -fields disk, serial-number, container-type, owner, path-lun-in-use-count, import-in-progress, is-foreign
----
+
您應該會看到根據纜線所預期的路徑數目（每個來源控制器至少有兩個路徑）。您也應該在遮罩陣列LUN之後、檢查事件記錄。

+
以下範例顯示了來自 Hitachi DF600F 陣列的來源 LUN。

+
[listing]
----
DataMig-ontap::*> storage disk show -array-name HITACHI_DF600F_1 -fields disk, serial-number, container-type, owner, path-lun-in-use-count, import-in-progress, is-foreign

disk     owner is-foreign container-type import-in-progress path-lun-in-use-count serial-number
-------- ----- ---------- -------------- ------------------ --------------------- -------------
HIT-1.2  -     false      unassigned     false        0,0,0,0,0,0,0,0       83017542001E
HIT-1.3  -     false      unassigned     false        0,0,0,0,0,0,0,0       83017542000E
HIT-1.14 -     false      unassigned     false        0,0,0,0,0,0,0,0       830175420019
3 entries were displayed.

----
. 使用序號在ONTAP來源 LUN 標記為外來 LUN：
+
[source, cli]
----
storage disk set-foreign-lun -serial-number <lun_serial_number> -is-foreign true
----
+
以下範例將 Hitachi DF600F 陣列中的來源 LUN 標記為外來 LUN。

+
[listing]
----
DataMig-ontap::*> storage disk set-foreign-lun { -serial-number 83017542001E }
                   -is-foreign true
DataMig-ontap::*> storage disk set-foreign-lun { -serial-number 83017542000E }
                   -is-foreign true
DataMig-ontap::*> storage disk set-foreign-lun { -serial-number 83017542000F }
                   -is-foreign true
----
. 驗證來源LUN是否標記為「Foreign（外部）」。
+
[source, cli]
----
storage disk show -array-name <array_name> -fields disk, serial-number, container-type, owner,import-in-progress, is-foreign
----
+
以下範例顯示來自 Hitachi DF600F 陣列的來源 LUN 被標記為外部。

+
[listing]
----
DataMig-ontap::*> storage disk show -array-name HITACHI_DF600F_1 -fields disk, serial-number, container-type, owner,import-in-progress, is-foreign

disk     owner is-foreign container-type import-in-progress serial-number
-------- ----- ---------- -------------- ------------------ -------------
HIT-1.2  -     true       foreign        false              83017542001E
HIT-1.3  -     true       foreign        false              83017542000E
HIT-1.4  -     true       foreign        false              83017542000F
3 entries were displayed.
----




== 步驟 2：建立並配置目標卷

在為 FLI 離線遷移建立 LUN 匯入關係之前，您必須在ONTAP儲存系統上建立磁碟區來包含將從外部陣列匯入的 LUN。

.關於此任務
從ONTAP 9.17.1 開始， ASA r2 系統支援使用 FLI 離線遷移對外部 LUN 進行資料遷移。 ASAASA系統與其他ONTAP系統（ASA、 AFF和FAS）在儲存層實施方面有所不同。在ASA r2 系統中，建立儲存單元（LUN 或命名空間）時會自動建立磁碟區。因此，您無需在建立 LUN 匯入關係之前建立磁碟區。如果您使用的是ASA r2 系統，則可以跳過此步驟。

詳細了解link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["ASA r2 系統"^] 。

.步驟
. 建立目的地Volume。
+
[source, cli]
----
volume create -vserver <SVM_name> -volume <volume_name> -aggregate <aggregate> -size <volume_size> -snapshot-policy default
----
+
以下範例建立一個名為 `winvol`在 `aggr1`大小為 100 GB 的聚合。

+
[listing]
----
DataMig-ontap::*> vol create -vserver datamig winvol aggr1 -size 100g
----
. 停用每個磁碟區上的預設 Snapshot 原則。
+
[source, cli]
----
volume modify -vserver <SVM_name> -volume <volume_name> -snapshot-policy none
----
+
如果在 FLI 遷移之前存在預設 Snapshot 副本，則磁碟區需要額外的空間來儲存變更的資料。

+
以下範例禁用 `winvol`體積。

+
[listing]
----
DataMig-ontap::> volume modify -vserver datamig -volume winvol -snapshot-policy none

Warning: You are changing the Snapshot policy on volume winvol to none.  Any Snapshot copies on this volume from the previous policy will not be deleted by
         this new Snapshot policy.
Do you want to continue? {y|n}: y
Volume modify successful on volume winvol of Vserver datamig.
----
. 將每個磁碟區的「fresse_rereserveoption」設為「0」、並將Snapshot原則設為「NONE」。
+
[source, cli]
----
vol modify -vserver <SVM_name> -volume * -fractional-reserve 0 –snapshot-policy none
----
+
以下範例設定 `fractional-reserve`選擇 `0`並將快照策略 `none`適用於 datamig SVM 中的所有磁碟區。

+
[listing]
----
DataMig-ontap::> vol modify -vserver datamig -volume * -fractional-reserve 0 –snapshot-policy none
Volume modify successful on volume winvol of Vserver datamig.
----
. 驗證您的音量設定。
+
[source, cli]
----
volume show -vserver <SVM_name> -volume * -fields fractional-reserve,snapshot-policy
----
+
factional-reserve 和 snapper-policy 設定應該是 `0`和 `none` ， 分別。

. 刪除任何現有的Snapshot複本。
+
[source, cli]
----
set advanced; snap delete –vserver <SVM_name> –volume <volume_name> –snapshot * -force true
----
+
[NOTE]
====
FLI移轉會修改目標LUN的每個區塊。如果在FLI移轉之前磁碟區上存在預設或其他Snapshot複本、則磁碟區會被填滿。需要進行FLI移轉之前、請先變更原則並移除任何現有的Snapshot複本。可在移轉後再次設定Snapshot原則。

====




== 步驟 3：建立目標 LUN 和 LUN 匯入關係

對於 FLI 離線遷移，必須建立ONTAP儲存系統上的目標 LUN 並將其對應到 igroup；然後必須在建立 LUN 匯入關係之前將其離線。

.關於此任務
從 ONTAP 9.17.1 開始，支援使用 FLI 離線遷移進行外國 LUN 的資料遷移，並支援  ASA r2 系統與其他ONTAP系統（ASA、 AFF和FAS）在儲存層實作方面有所不同。ASA r2 系統中，建立儲存單元（LUN 或命名空間）時會自動建立磁碟區。每個磁碟區僅包含一個儲存單元。因此，對於ASA r2 系統，您無需在 `-path`建立 LUN 時，請提供此選項；您應該包含儲存單元路徑。

.步驟
. 建立目標 LUN。
+
[source, cli]
----
lun create -vserver <SVM_name> -path <volume_path|storage_unit_path> -ostype <os_type> -foreign-disk <serial_number>
----
+
以下範例在 `datamig`具有指定路徑和外部磁碟序號的 SVM。  `-ostype`選項指定 LUN 的作業系統類型。

+
[listing]
----
DataMig-ontap::*> lun create -vserver datamig -path /vol/winvol/bootlun -ostype windows_2008 -foreign-disk 83017542001E

Created a LUN of size 40g (42949672960)

Created a LUN of size 20g (21474836480)
DataMig-ontap::*> lun create -vserver datamig -path /vol/linuxvol/lvmlun1 -ostype linux -foreign-disk 830175420011

Created a LUN of size 2g (2147483648)
DataMig-ontap::*> lun create -vserver datamig -path /vol/esxvol/bootlun -ostype vmware -foreign-disk 830175420014

Created a LUN of size 20g (21474836480)
----
+
[NOTE]
====
這 `lun create`指令會根據分割區偏移量偵測 LUN 的大小和對齊方式，並使用 Foreign-Disk 選項相應地建立 LUN。某些 I/O 總是會顯示為部分寫入，因此看起來會不對齊。例如，資料庫日誌。

====
. 驗證新建立的 LUN 的大小和來源 LUN。
+
[source, cli]
----
lun show -vserver <SVM_name> -fields vserver, path, state, mapped, type, size
----
+
以下範例顯示了在 `datamig` SVM 及其路徑、狀態、映射狀態、類型和大小。

+
[listing]
----
DataMig-ontap::*> lun show -vserver datamig

Vserver   Path                            State   Mapped   Type        Size
--------- ------------------------------- ------- -------- -------- --------
datamig   /vol/esxvol/bootlun             online  unmapped vmware       20GB
datamig   /vol/esxvol/linuxrdmvlun        online  unmapped linux         2GB
datamig   /vol/esxvol/solrdmplun          online  unmapped solaris       2GB
datamig   /vol/winvol/gdrive              online  unmapped windows_2008  3GB
4 entries were displayed.
----
. 如果您執行的是ONTAP 9.15.1 或更高版本，請停用新建立的 LUN 的空間分配。
+
在ONTAP 9.15.1 及更高版本中，新建立的 LUN 預設啟用空間分配。

+
[source, cli]
----
lun modify -vserver <vserver_name> -volume <volume_name> -lun <lun_name> -space-allocation disabled
----
. 驗證空間分配是否已停用。
+
[source, cli]
----
lun show -vserver <vserver_name> -volume <volume_name> -lun <lun_name> -fields space-allocation
----
. 建立協定FCP的主機igroup，並新增主機啟動器。
+
[source, cli]
----
lun igroup create -ostype <os_type> -protocol fcp -vserver <SVM_name> -igroup <igroup_name> -initiator <initiator_wwpn1>,<initiator_wwpn2>
----
+
從網站調查規劃工作表的儲存群組部分中尋找啟動器 WWPN。

+
以下範例為具有指定作業系統類型和啟動器的目標 LUN 建立 igroup。

+
[listing]
----
DataMig-ontap::*> lun igroup create -ostype windows -protocol fcp -vserver datamig -igroup dm-rx200s6-21 -initiator 21:00:00:24:ff:30:14:c4,21:00:00:24:ff:30:14:c5

DataMig-ontap::*> lun igroup create -ostype linux -protocol fcp -vserver datamig  -igroup dm-rx200s6-22 -initiator 21:00:00:24:ff:30:04:85,21:00:00:24:ff:30:04:84

DataMig-ontap::*> lun igroup create -ostype vmware -protocol fcp -vserver datamig -igroup dm-rx200s6-20 -initiator 21:00:00:24:ff:30:03:ea,21:00:00:24:ff:30:03:eb
----
+
[NOTE]
====
使用與來源相同的LUN ID。請參閱現場調查規劃工作表的來源LUN區段。

====
. 將目標 LUN 對應到 igroup。
+
[source, cli]
----
lun map -vserver <SVM_name> -path <volume_path|storage_unit_path> -igroup <igroup_name> -lun-id <lun_id>
----
+
以下範例使用指定的路徑和 LUN ID 將目標 LUN 對應到其各自的 igroup。

+
[listing]
----
DataMig-ontap::*> lun map -vserver datamig -path /vol/winvol/bootlun -igroup dm-rx200s6-21 -lun-id 0
DataMig-ontap::*> lun map -vserver datamig -path /vol/linuxvol/bootlun -igroup dm-rx200s6-22 -lun-id 0
DataMig-ontap::*> lun map -vserver datamig -path /vol/esxvol/bootlun -igroup dm-rx200s6-20 -lun-id 0
----
. 使目的地LUN離線。
+
[source, cli]
----
lun offline -vserver <SVM_name> -path <volume_path|storage_unit_path>
----
+
以下範例將使 `datamig`支援向量機。

+
[listing]
----
DataMig-ontap::*> lun offline -vserver datamig -path /vol/esxvol/bootlun
DataMig-ontap::*> lun offline -vserver datamig -path /vol/esxvol/linuxrdmvlun
DataMig-ontap::*> lun offline -vserver datamig -path /vol/esxvol/solrdmplun
----
. 在目標 LUN 和來源 LUN 之間建立 LUN 匯入關係。
+
[source, cli]
----
lun import create -vserver <SVM_name> -path <volume_path|storage_unit_path> -foreign-disk <serial_number>
----
+
以下範例為 `datamig` SVM 及其各自的路徑和外部磁碟序號。

+
[listing]
----
DataMig-ontap::*> lun import create -vserver datamig -path /vol/winvol/bootlun -foreign-disk 83017542001E
DataMig-ontap::*> lun import create -vserver datamig -path /vol/linuxvol/ext3lun -foreign-disk 830175420013
DataMig-ontap::*> lun import create -vserver datamig -path /vol/esxvol/linuxrdmvlun -foreign-disk 830175420018
DataMig-ontap::*> lun import create -vserver datamig -path /vol/esxvol/solrdmplun -foreign-disk 830175420019
----
. 驗證 LUN 導入關係是否已建立。
+
[source, cli]
----
lun import show -vserver <SVM_name> -fields vserver, foreign-disk, path, operation, admin-state, operational-state, percent-complete
----
+
以下範例顯示了為目標 LUN 建立的 LUN 匯入關係 `datamig` SVM 及其各自的外部磁碟和路徑。

+
[listing]
----
DataMig-ontap::*> lun import show -vserver datamig
vserver foreign-disk   path                operation admin operational percent
                                         in progress state state       complete
-------------------------------------------------------------------------------
datamig 83017542000E   /vol/winvol/fdrive  import    stopped
                                                           stopped            0
datamig 83017542000F   /vol/winvol/gdrive  import    stopped
                                                           stopped            0
datamig 830175420010   /vol/linuxvol/bootlun
                                           import    stopped
                                                           stopped            0
3 entries were displayed.
----


.下一步是什麼？
link:task_fli_offline_importing_the_data.html["將資料從外部 LUN 匯入到ONTAP LUN"] 。

.相關資訊
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/What_is_an_unaligned_I%2F%2FO%3F["了解有關未對齊 I/O 的更多信息"] 。
* https://docs.netapp.com/us-en/ontap/san-admin/enable-space-allocation.html["了解有關為 SAN 協定啟用空間分配的更多信息"] 。

