---
permalink: san-migration/map-source-lun-to-destination-online-migration.html 
sidebar: sidebar 
keywords: fli online, perform, disruptive, cutover 
summary: 此範例提供執行FLI線上移轉程序中斷轉換的一般步驟。 
---
= 將來源 LUN 對應到ONTAP陣列以進行 FLI 線上遷移
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
若要從外部陣列 LUN 匯入數據，必須先在外部陣列上取消映射該 LUN，然後將其重新對應到您的ONTAP儲存系統。用於取消外部陣列上 LUN 映射的命令因陣列供應商而異。您應該遵循整個過程提供的步驟，並參閱外部陣列的文件以了解特定命令。

.開始之前
從 igroup 移除主機（啟動器）會影響對應到該 igroup 的所有 LUN。為防止外部陣列上的其他 LUN 中斷，要遷移的 LUN 必須是對應到其 igroup 的唯一 LUN。如果還有其他 LUN 共用該 igroup，請將它們重新對應到其他 igroup，或專門為要移轉的 LUN 建立一個新的 igroup。請參閱供應商文件以了解相應的命令。

.步驟
. 在外部陣列上、顯示來源LUN對應的儲存群組。
+
請參閱廠商文件以取得適當的命令。

. 如果要匯入的 LUN 用於 ESXi 主機，請查看並遵循link:reference_esxi_caw_ats_remediation.html["ESXi CAW/ATS補救"] 。
. 從主機取消對應來源LUN。
+
[NOTE]
====
執行「unmap」命令之後、就會立即開始中斷作業。一般而言、中斷時間可在幾分鐘內測量。中斷時間是指將主機重新指向新的NetApp目標並掃描LUN所需的時間。

====
. 驗證主機啟動器是否不再存在。
. 在實體叢集上、將目的地LUN上線、然後確認其已對應。ONTAP
+
[source, cli]
----
lun online -vserver <SVM_name> -path <volume_path|storage_unit_path>
----
. 驗證LUN是否在線上。
+
[source, cli]
----
lun show -vserver <SVM_name>
----
. 重新掃描主機上的磁碟、在ONTAP 支援對象上找到LUN、然後確認DSM已宣告LUN。
+
[NOTE]
====
中斷時間到此結束。

====
. 請確認您可以查看所有預期路徑、並檢查事件記錄以確認不存在任何錯誤。


.結果
此遷移的破壞性部分已完成，除非存在破壞性的未完成的主機修復任務（在分析和規劃階段確定）。

LUN已連線並對應、主機現在正在掛載新的ONTAP託管LUN。讀取內容會透過ONTAP the sunse-Array傳送到來源LUN、寫入內容會寫入新的ONTAP託管LUN和原始來源LUN。來源LUN和目的地LUN會保持同步、直到移轉完成且LUN關係中斷為止。

.下一步是什麼？
link:task_fli_online_importing_the_data.html["從外部 LUN 匯入數據"] 。
