---
permalink: san-migration/remove-lun-import-relationship-offline.html 
sidebar: sidebar 
keywords: fli offline, verify, migration, results 
summary: 驗證工作是選用的、但建議使用。這是來源LUN與目的地LUN的區塊間比較。驗證工作所需時間幾乎與移轉時間相同或稍微長一點。 
---
= 在ONTAP FLI 離線遷移後刪除 LUN 導入關係
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
外部 LUN 匯入 (FLI) 離線遷移完成後，可以安全地移除 LUN 匯入關係。此時，主機正在存取新的NetApp陣列，執行對新ONTAP LUN 的所有 I/O，且來源 LUN 不再使用，因此不再需要匯入關係。

從 ONTAP 9.17.1 開始，支援使用 FLI 離線遷移進行外國 LUN 的資料遷移，並支援 link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["ASA r2 系統"^].ASA r2 系統與其他ONTAP系統（ASA、 AFF和FAS）在儲存層實作方面有所不同。ASA r2 系統中，建立儲存單元（LUN 或命名空間）時會自動建立磁碟區。每個磁碟區僅包含一個儲存單元。因此，對於ASA r2 系統，您無需在 `-path`建立 LUN 時，請提供此選項；您應該包含儲存單元路徑。

.步驟
. 刪除匯入關係以移除資料匯入作業。
+
[source, cli]
----
lun import delete -vserver <SVM_name> -path <volume_path|storage_unit_path>
----
+
此範例顯示用於刪除 *winvol* 捲和 *datamig* SVM 中名為 *bootlun*、*fdrive* 和 *gdrive* 的 LUN 的導入關係的命令。

+
[listing]
----
DataMig-ontap::*> lun import delete -vserver datamig -path /vol/winvol/bootlun

DataMig-ontap::*> lun import delete -vserver datamig -path /vol/winvol/fdrive

DataMig-ontap::*> lun import delete -vserver datamig -path /vol/winvol/gdrive
----
. 驗證導入作業是否已刪除。
+
[source, cli]
----
lun import show -vserver <SVM_name>
----
+
此範例顯示用於驗證是否已刪除 *datamig* SVM 的導入作業的命令。

+
[listing]
----
DataMig-ontap::*> lun import show -vserver datamig
There are no entries matching your query.
----
. 將Foreign LUN（外部LUN）屬性標記為「假」。
+
[source, cli]
----
storage disk modify -serial-number <serial_number> -is-foreign false
----
+
此範例顯示將外部 LUN 屬性標記為 `false`對於 *winvol* 捲和 *datamig* SVM 中名為 *bootlun*、*fdrive* 和 *gdrive* 的 LUN。

+
[listing]
----
DataMig-ontap::*> storage disk modify { -serial-number 83017542001E }
-is-foreign false

DataMig-ontap::*> storage disk modify { -serial-number 83017542000E }
-is-foreign false

DataMig-ontap::*> storage disk modify { -serial-number 83017542000F }
-is-foreign false
----
. 驗證外部 LUN 是否標記為 `false` 。
+
[source, cli]
----
storage disk show -array-name <array_name> -fields disk, serial-number, container-type, owner, import-in-progress, is-foreign
----
+
此範例顯示用於驗證外部 LUN 是否標記為 `false`在 *HITACHI_DF600F_1* 陣列上。

+
[listing]
----
DataMig-ontap::*> storage disk show -array-name HITACHI_DF600F_1 -fields disk, serial-number, container-type, owner,import-in-progress, is-foreign

disk     owner is-foreign container-type import-in-progress serial-number
-------- ----- ---------- -------------- ------------------ -------------
HIT-1.2  -     false      unassigned     false              83017542001E
HIT-1.3  -     false      unassigned     false              83017542000E
HIT-1.4  -     false      unassigned     false              83017542000F
3 entries were displayed.
----
. 使目標 LUN 連線。
+
[source, cli]
----
lun online -vserver <SVM_name> -path <volume_path|storage_unit_path>
----
+
此範例顯示使 *winvol* 捲和 *datamig* SVM 中名為 *bootlun*、*fdrive* 和 *gdrive* 的 LUN 的目標 LUN 線上的命令。

+
[listing]
----
DataMig-ontap::*> lun online -vserver datamig -path /vol/winvol/bootlun

DataMig-ontap::*> lun online -vserver datamig -path /vol/winvol/fdrive

DataMig-ontap::*> lun online -vserver datamig -path /vol/winvol/gdrive
----
. 驗證LUN是否在線上。
+
[source, cli]
----
lun show -vserver <SVM_name>
----
+
此範例顯示用於驗證 *datamig* SVM 的 LUN 是否在線的命令。

+
[listing]
----
DataMig-ontap::*> lun show -vserver datamig
Vserver   Path                            State   Mapped   Type        Size
--------- ------------------------------- ------- -------- -------- --------
datamig   /vol/esxvol/bootlun             online  mapped   vmware       20GB
datamig   /vol/esxvol/linuxrdmvlun        online  mapped   linux         2GB
datamig   /vol/esxvol/solrdmplun          online  mapped   solaris       2GB
3 entries were displayed.
----
. 或者，查看事件日誌以驗證遷移結果。
+
[source, cli]
----
event log show –event fli*
----
+
此範例顯示用於查看 FLI 遷移結果的事件日誌的命令的範例輸出。

+
[listing]
----
DataMig-ontap::*> event log  show –event fli*

7/7/2014 18:37:21   DataMig-ontap-01 INFORMATIONAL fli.lun.verify.complete: Import verify of foreign LUN 83017542001E of size 42949672960 bytes from array model DF600F belonging to vendor HITACHI  with NetApp LUN QvChd+EUXoiS is successfully completed.
7/7/2014 18:37:15   DataMig-ontap-01 INFORMATIONAL fli.lun.verify.complete: Import verify of foreign LUN 830175420015 of size 42949672960 bytes from array model DF600F belonging to vendor HITACHI  with NetApp LUN QvChd+EUXoiX is successfully completed.
7/7/2014 18:02:21   DataMig-ontap-01 INFORMATIONAL fli.lun.import.complete: Import of foreign LUN 83017542000F of size 3221225472 bytes from array model DF600F belonging to vendor HITACHI  is successfully completed. Destination NetApp LUN is QvChd+EUXoiU.
----


.下一步是什麼？
link:concept_fli_offline_post_migration_tasks.html["執行 FLI 離線遷移的遷移後任務"] 。
