---
permalink: san-migration/task_fli_offline_verifying_migration_results.html 
sidebar: sidebar 
keywords: fli offline, verify, migration, results 
summary: 驗證工作是選用的、但建議使用。這是來源LUN與目的地LUN的區塊間比較。驗證工作所需時間幾乎與移轉時間相同或稍微長一點。 
---
= 驗證ONTAP FLI 離線遷移結果
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
將 LUN 從外部陣列遷移到ONTAP儲存系統後，FLI 可以對來源 LUN 和目標 LUN 進行逐塊比較，以驗證遷移是否完整且準確。遷移驗證所需的時間與遷移過程大致相同（或略長）。

不需要進行遷移驗證，但強烈建議進行。

.關於此任務
從 ONTAP 9.17.1 開始，支援使用 FLI 離線遷移進行外國 LUN 的資料遷移，並支援  ASA r2 系統與其他ONTAP系統（ASA、 AFF和FAS）在儲存層實作方面有所不同。ASA r2 系統中，建立儲存單元（LUN 或命名空間）時會自動建立磁碟區。每個磁碟區僅包含一個儲存單元。因此，對於ASA r2 系統，您無需在 `-path`建立 LUN 時，請提供此選項；您應該包含儲存單元路徑。

.步驟
. 開始LUN遷移驗證。
+
[source, cli]
----
lun import verify start -vserver <SVM_name> -path <volume_path|storage_unit_path>
----
+
此範例顯示用於啟動 *winvol* 捲和 *datamig* SVM 中名為 *bootlun*、*fdrive* 和 *gdrive* 的 LUN 遷移驗證的命令。

+
[listing]
----
DataMig-ontap::*> lun import verify start -vserver datamig -path /vol/winvol/bootlun

DataMig-ontap::*> lun import verify start -vserver datamig -path /vol/winvol/fdrive

DataMig-ontap::*> lun import verify start -vserver datamig -path /vol/winvol/gdrive
----
. 監控驗證狀態。
+
[source, cli]
----
lun import show -vserver <SVM_name> -fields vserver, foreign-disk, path, admin-state, operational-state, percent-complete, imported-blocks, total-blocks, estimated-remaining-duration
----
+
此範例顯示用於監控 *datamig* SVM 的驗證狀態的命令。

+
[listing]
----
DataMig-ontap::*> lun import show -vserver datamig -fields vserver, foreign-disk, path, admin-state, operational-state, percent-complete, imported-blocks, total-blocks, , estimated-remaining-duration

vserver foreign-disk path               admin-state operational-state percent-complete imported-blocks total-blocks estimated-remaining-duration
------- ------------ ------------------ ----------- ----------------- ---------------- --------------- ------------ ----------------------------
datamig 83017542000E /vol/winvol/fdrive started     in_progress       57               -               4194304      00:01:19
datamig 83017542000F /vol/winvol/gdrive started     in_progress       40               -               6291456      00:02:44
datamig 830175420010 /vol/linuxvol/bootlun
                                        started     in_progress       8                -               41943040     00:20:29
3 entries were displayed.
----
+
您可以執行相同的命令來追蹤驗證進度。驗證作業成功完成後，*operational-state* 會顯示 *completed* 狀態。

. 停止 LUN 驗證。
+
[source, cli]
----
lun import verify stop -vserver <SVM_name> -path <volume_path|storage_unit_path>
----
+
此範例顯示停止 *datamig* SVM 的 LUN 驗證的命令。

+
[listing]
----
DataMig-ontap::*> lun import verify stop -vserver datamig -path /vol/esxvol/winrdmplun
----
+
必須先明確停止 LUN 導入驗證，然後才能將 LUN 恢復連線。否則，  `lun online`命令失敗。即使狀態顯示驗證已完成，也必須手動執行此步驟。



.下一步是什麼？
link:remove-lun-import-relationship-offline.html["解除LUN導入關係"] 。
