---
permalink: san-migration/task_fli_transition_preparing_source_and_destination_arrays.html 
sidebar: sidebar 
keywords: prepare, source, destination, arrays, migration 
summary: 若要準備FLI 7-mode to ONTAP VMware移轉、請驗證主機和來源LUN路徑及其他詳細資料。 
---
= 準備要移轉的來源陣列和目的地陣列
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
若要準備FLI 7-mode to ONTAP VMware移轉、請驗證主機和來源LUN路徑及其他詳細資料。

.步驟
. 在本系統中、改為「進階」權限等級。ONTAP
+
[listing]
----
cluster::> set adv

Warning: These advanced commands are potentially dangerous; use them only when directed to do so by NetApp personnel.
Do you want to continue? {y|n}: y

cluster::*>
----
. 確認來源陣列可在目的地控制器上看到。
+
[listing]
----
cluster::*> storage array show
Prefix                         Name   Vendor            Model Options
-------- ---------------------------- -------- ---------------- ----------
NET-1                    NETAPP_LUN_1   NETAPP              LUN

cluster::*> storage array config show -array-name NETAPP_LUN_1
             LUN   LUN
Node         Group Count                   Array Name       Array Target Port Initiator
------------ ----- ----- ---------------------------- ----------------------- ---------
ontaptme-fc-cluster-01
                 1     2                 NETAPP_LUN_1        500a0981880b813d        0d
                                                             500a0981980b813d        0d
ontaptme-fc-cluster-02
                 1     2                 NETAPP_LUN_1        500a0981880b813d        0d
                                                             500a0981980b813d        0d
4 entries were displayed.

Warning: Configuration errors were detected.  Use 'storage errors show' for detailed information.
----
. 檢視所列任何儲存錯誤的詳細資料。某些錯誤可能需要先採取行動才能繼續。不過、下列範例「此裝置是ONTAP（R）LUN」中顯示的錯誤可以安全地忽略。
+
[NOTE]
====
錯誤訊息「此裝置為ONTAP（R\）LUN」。這是因為FLI仰賴FlexArray 不支援虛擬ONTAP 化功能的不支援虛擬化的ONTAPFLI能夠匯入LUN、FlexArray 但不支援虛擬化LUN。

====
+
[listing]
----
cluster::*> storage errors show
Disk: NET-1.1
UID: 60A98000:44306931:452B4738:5767366B:00000000:00000000:00000000:00000000:00000000:00000000
--------------------
NET-1.1 (60a9800044306931452b47385767366b): This device is an ONTAP(R) LUN.

Disk: NET-1.2
UID: 60A98000:44306931:452B4738:5767366D:00000000:00000000:00000000:00000000:00000000:00000000
--------------------
NET-1.2 (60a9800044306931452b47385767366d): This device is an ONTAP(R) LUN.

2 entries were displayed.
----
. 顯示來源LUN詳細資料。
+
[listing]
----
cluster::*> storage array config show -array-name NETAPP_LUN_1 -instance

           Controller Name: ontaptme-fc-cluster-01
                 LUN Group: 1
        Array Target Ports: 500a0981880b813d
                 Initiator: 0d
                Array Name: NETAPP_LUN_1
   Target Side Switch Port: stme-5010-4:2-6
Initiator Side Switch Port: stme-5010-4:2-3
      Number of array LUNs: 2

           Controller Name: ontaptme-fc-cluster-01
                 LUN Group: 1
        Array Target Ports: 500a0981980b813d
                 Initiator: 0d
                Array Name: NETAPP_LUN_1
   Target Side Switch Port: stme-5010-4:2-5
Initiator Side Switch Port: stme-5010-4:2-3
      Number of array LUNs: 2

~~~~~~ Output truncated ~~~~~~~
4 entries were displayed.

Warning: Configuration errors were detected.  Use 'storage errors show' for detailed information.
----
. 驗證是否已透過所有啟動器連接埠探索來源陣列。
+
[listing]
----
cluster::*> storage array config show -array-name NETAPP_LUN_1
             LUN   LUN
Node         Group Count                   Array Name       Array Target Port Initiator
------------ ----- ----- ---------------------------- ----------------------- ---------
ontaptme-fc-cluster-01
                 1     2                 NETAPP_LUN_1        500a0981880b813d        0d
                                                             500a0981980b813d        0d
ontaptme-fc-cluster-02
                 1     2                 NETAPP_LUN_1        500a0981880b813d        0d
                                                             500a0981980b813d        0d
4 entries were displayed.

Warning: Configuration errors were detected.  Use 'storage errors show' for detailed information.
----
. 列出從7-Mode儲存設備對應的LUN。驗證磁碟內容和路徑。
+
[listing]
----
cluster::*> storage disk show -array-name NETAPP_LUN_1 -instance
                  Disk: NET-1.1
        Container Type: unassigned
            Owner/Home: -  / -
               DR Home: -
    Stack ID/Shelf/Bay: -  / -  / -
                   LUN: 0
                 Array: NETAPP_LUN_1
                Vendor: NETAPP
                 Model: LUN
         Serial Number: D0i1E+G8Wg6k
                   UID: 60A98000:44306931:452B4738:5767366B:00000000:00000000:00000000:00000000:00000000:00000000
                   BPS: 512
         Physical Size: -
              Position: present
Checksum Compatibility: block
             Aggregate: -
                  Plex: -
Paths:
                                LUN  Initiator Side        Target Side                                                        Link
Controller         Initiator     ID  Switch Port           Switch Port           Acc Use  Target Port                TPGN    Speed      I/O KB/s          IOPS
------------------ ---------  -----  --------------------  --------------------  --- ---  -----------------------  ------  -------  ------------  ------------
ontaptme-fc-cluster-02
                   0d             0  stme-5010-4:2-4       stme-5010-4:2-6       ANO RDY  500a0981880b813d              1   4 Gb/S             0             0
ontaptme-fc-cluster-02
                   0d             0  stme-5010-4:2-4       stme-5010-4:2-5       AO  INU  500a0981980b813d              0   4 Gb/S             0             0
ontaptme-fc-cluster-01
                   0d             0  stme-5010-4:2-3       stme-5010-4:2-6       ANO RDY  500a0981880b813d              1   4 Gb/S             0             0
ontaptme-fc-cluster-01
                   0d             0  stme-5010-4:2-3       stme-5010-4:2-5       AO  INU  500a0981980b813d              0   4 Gb/S             0             0

Errors:
NET-1.1 (60a9800044306931452b47385767366b): This device is a ONTAP(R) LUN.
~~~~~~ Output truncated ~~~~~~~
2 entries were displayed.
----
. 驗證來源LUN是否標記為「Foreign（外部）」。
+
[listing]
----
cluster::*> storage disk show -array-name NETAPP_LUN_1
                     Usable           Disk    Container   Container
Disk                   Size Shelf Bay Type    Type        Name      Owner
---------------- ---------- ----- --- ------- ----------- --------- --------
NET-1.1                   -     -   - LUN     unassigned  -         -
NET-1.2                   -     -   - LUN     foreign     -         -
2 entries were displayed.
----
. 在FLI LUN匯入命令中使用序號。列出所有外部LUN及其序號。
+
[listing]
----
cluster::*> storage disk show -container-type foreign -fields serial-number
disk    serial-number
------- --------------------------------
NET-1.2 D0i1E+G8Wg6m
----
. 建立目標LUN。「LUN create」命令會根據分割區偏移量來偵測大小和對齊方式、然後使用Foreign磁碟引數來建立LUN
+
[listing]
----
cluster::*> vol create -vserver fli_72C -volume flivol -aggregate aggr1 -size 10G
[Job 12523] Job succeeded: Successful
----
. 驗證Volume。
+
[listing]
----
cluster::*> vol show -vserver fli_72C
Vserver   Volume       Aggregate    State      Type       Size  Available Used%
--------- ------------ ------------ ---------- ---- ---------- ---------- -----
fli_72C   flivol       aggr1        online     RW         10GB     9.50GB    5%
fli_72C   rootvol      aggr1        online     RW          1GB    972.6MB    5%
2 entries were displayed.
----
. 建立目標LUN。
+
[listing]
----
cluster::*> lun create -vserver fli_72C -path /vol/flivol/72Clun1 -ostype windows_2008 -foreign-disk D0i1E+G8Wg6m

Created a LUN of size 3g (3224309760)
----
. 驗證新LUN。
+
[listing]
----
cluster::*> lun show -vserver fli_72C
Vserver   Path                            State   Mapped   Type        Size
--------- ------------------------------- ------- -------- -------- --------
fli_72C   /vol/flivol/72Clun1             online  unmapped windows_2008
                                                                      3.00GB
----
. 使用主機啟動器建立傳輸協定FCP的群組。
+
[listing]
----
cluster::*> lun igroup create -vserver fli_72C -igroup 72C_g1 -protocol fcp -ostype windows –initiator 10:00:00:00:c9:e6:e2:79

cluster::*> lun igroup show -vserver fli_72C -igroup 72C_g1
          Vserver Name: fli_72C
           Igroup Name: 72C_g1
              Protocol: fcp
               OS Type: windows
Portset Binding Igroup: -
           Igroup UUID: 7bc184b1-dcac-11e4-9a88-00a0981cc318
                  ALUA: true
            Initiators: 10:00:00:00:c9:e6:e2:79 (logged in)
----
. 將測試LUN對應至測試igroup。
+
[listing]
----
cluster::*> lun map -vserver fli_72C -path /vol/flivol/72Clun1 -igroup 72C_g1

cluster::*> lun mapping show -vserver fli_72C
Vserver    Path                                      Igroup   LUN ID  Protocol
---------- ----------------------------------------  -------  ------  --------
fli_72C    /vol/flivol/72Clun1                       72C_g1        0  fcp
----
. 離線測試LUN。
+
[listing]
----
cluster::*> lun offline -vserver fli_72C -path /vol/flivol/72Clun1

Warning: This command will take LUN "/vol/flivol/72Clun1" in Vserver "fli_72C" offline.
Do you want to continue? {y|n}: y

cluster::*> lun show -vserver fli_72C
Vserver   Path                            State   Mapped   Type        Size
--------- ------------------------------- ------- -------- -------- --------
fli_72C   /vol/flivol/72Clun1             offline mapped   windows_2008
                                                                      3.00GB
----
. 在新LUN與外部LUN之間建立匯入關係。
+
[listing]
----
cluster::*> lun import create -vserver fli_72C -path /vol/flivol/72Clun1 -foreign-disk D0i1E+G8Wg6m

cluster::*> lun import show -vserver fli_72C -path /vol/flivol/72Clun1
vserver foreign-disk   path                operation admin operational percent
                                         in progress state state       complete
-------------------------------------------------------------------------------
fli_72C D0i1E+G8Wg6m   /vol/flivol/72Clun1 import    stopped
                                                           stopped            0
----

