---
permalink: san-migration/task_fli_online_preparing_the_lun_path.html 
sidebar: sidebar 
keywords: fli online, prepare, lun path 
summary: 若要準備FLI線上移轉、請驗證主機和來源LUN路徑及其他詳細資料。 
---
= FLI線上：準備LUN路徑
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
若要準備FLI線上移轉、請驗證主機和來源LUN路徑及其他詳細資料。

.步驟
. 在本系統中、將權限等級變更為「進階」ONTAP 。
+
[listing]
----
cluster::> set adv

Warning: These advanced commands are potentially dangerous; use them only when directed to do so by NetApp personnel.
Do you want to continue? {y|n}: y
----
. 確認來源陣列可在目的地控制器上看到。
+
[listing]
----

        cluster::*> storage array show
Prefix                         Name   Vendor            Model Options
-------- ---------------------------- -------- ---------------- ----------
DGC-1                      DGC_LUNZ_1      DGC             LUNZ
1 entries were displayed.
----
. 顯示來源LUN詳細資料。
+
[listing]
----
cluster::*> storage array config show -array-name DGC_LUNZ_1 -instance

           Controller Name: ontaptme-fc-cluster-01
                 LUN Group: 0
        Array Target Ports: 500601643ea067da
                 Initiator: 0c
                Array Name: DGC_LUNZ_1
   Target Side Switch Port: stme-5010-3:2-1
Initiator Side Switch Port: stme-5010-3:2-3
      Number of array LUNs: 1

           Controller Name: ontaptme-fc-cluster-01
                 LUN Group: 0
        Array Target Ports: 500601653ea067da
                 Initiator: 0d
                Array Name: DGC_LUNZ_1
   Target Side Switch Port: stme-5010-4:2-1
Initiator Side Switch Port: stme-5010-4:2-3
      Number of array LUNs: 1
~~~~~~~~~~~ output truncated for readability ~~~~~~~~~~~~~~~~~
8 entries were displayed.
----
. 驗證是否已透過所有啟動器連接埠探索來源陣列。
+
[listing]
----
cluster::*> storage array config show -array-name DGC_LUNZ_1
             LUN   LUN
Node         Group Count                   Array Name       Array Target Port Initiator
------------ ----- ----- ---------------------------- ----------------------- ---------
ontaptme-fc-cluster-01
                 0     1                   DGC_LUNZ_1        500601643ea067da        0c
                                                             500601653ea067da        0d
                                                             5006016c3ea067da        0c
                                                             5006016d3ea067da        0d
ontaptme-fc-cluster-02
                 0     1                   DGC_LUNZ_1        500601643ea067da        0c
                                                             500601653ea067da        0d
                                                             5006016c3ea067da        0c
                                                             5006016d3ea067da        0d
8 entries were displayed.
----
+
[NOTE]
====
下列輸出中的自動換行字詞沒有意義。

====
. 列出從來源儲存設備對應的LUN。驗證磁碟內容和路徑。
+
[listing]
----
cluster::*> storage disk show -array-name DGC_LUNZ_1 -instance
                  Disk: DGC-1.9
        Container Type: unassigned
            Owner/Home: -  / -
               DR Home: -
    Stack ID/Shelf/Bay: -  / -  / -
                   LUN: 0
                 Array: DGC_LUNZ_1
                Vendor: DGC
                 Model: VRAID
         Serial Number: 600601603F103100662E70861000E511
                   UID: 60060160:3F103100:662E7086:1000E511:00000000:00000000:00000000:00000000:00000000:00000000
                   BPS: 512
         Physical Size: -
              Position: present
Checksum Compatibility: block
             Aggregate: -
                  Plex: -
Paths:
                               LUN  Initiator Side        Target Side                                                        Link
Controller         Initiator     ID  Switch Port           Switch Port           Acc Use  Target Port                TPGN    Speed      I/O KB/s          IOPS
------------------ ---------  -----  --------------------  --------------------  --- ---  -----------------------  ------  -------  ------------  ------------
ontaptme-fc-cluster-02
                   0c             0  stme-5010-3:2-4       stme-5010-3:2-2       AO  INU  5006016c3ea067da              2   4 Gb/S             0             0
ontaptme-fc-cluster-02
                   0d             0  stme-5010-4:2-4       stme-5010-4:2-2       AO  INU  5006016d3ea067da              2   4 Gb/S             0             0
ontaptme-fc-cluster-02
                   0d             0  stme-5010-4:2-4       stme-5010-4:2-1       ANO RDY  500601653ea067da              1   4 Gb/S             0             0

Errors:
-
----
. 檢視來源LUN。
+
[listing]
----
cluster::*> storage disk show -array-name DGC_LUNZ_1
                     Usable           Disk    Container   Container
Disk                   Size Shelf Bay Type    Type        Name      Owner
---------------- ---------- ----- --- ------- ----------- --------- --------
DGC-1.9                   -     -   - LUN     unassigned  -         -
----
. 將來源LUN標示為外部LUN。
+
[listing]
----
cluster::*> storage disk set-foreign-lun -is-foreign true -disk DGC-1.9
----
. 驗證來源LUN是否標記為「Foreign（外部）」。
+
[listing]
----
cluster::*> storage disk show -array-name DGC_LUNZ_1
                     Usable           Disk    Container   Container
Disk                   Size Shelf Bay Type    Type        Name      Owner
---------------- ---------- ----- --- ------- ----------- --------- --------
DGC-1.9
----
. 在FLI LUN匯入命令中使用序號。列出所有外部LUN及其序號。
+
[listing]
----
cluster::*> storage disk show -container-type foreign -fields serial-number
disk    serial-number
------- --------------------------------
DGC-1.9 600601603F103100662E70861000E511
----
. 建立目的地Volume。
+
[listing]
----
cluster::*> vol create -vserver fli -volume fli_vol -aggregate aggr1 -size 2t
[Job 13888] Job succeeded: Successful
----
. 驗證Volume。
+
[listing]
----
cluster::*> vol show -vserver fli
Vserver   Volume       Aggregate    State      Type       Size  Available Used%
--------- ------------ ------------ ---------- ---- ---------- ---------- -----
fli       fli_root     aggr1        online     RW          1GB    972.6MB    5%
fli       fli_vol      aggr1        online     RW          2TB     1.90TB    5%
2 entries were displayed.
----
. 將每個磁碟區的fraction保留選項設為「0」、並將Snapshot原則設為「無」。
+
[listing]
----
cluster::*> vol modify -vserver datamig -volume * -fractional-reserve 0 –snapshot-policy none
Volume modify successful on volume winvol of Vserver datamig.
----
. 檢查您的Volume設定。
+
[listing]
----
cluster::*> vol show -vserver datamig -volume * -fields fractional-reserve,snapshot-policy
vservervolumesnapshot-policyfractional-reserve
-----------------------------------------------
datamigdatamig_rootnone0%
datamigwinvolnone0%
Volume modify successful on volume winvol of Vserver datamig.
----
. 刪除任何現有的Snapshot複本。
+
[listing]
----
cluster::*> set advanced; snap delete –vserver datamig –vol winvol –snapshot * -force true
1 entry was acted on.
----
+
[NOTE]
====
FLI移轉會修改目標LUN的每個區塊。如果在FLI移轉之前磁碟區上存在預設或其他Snapshot複本、則磁碟區會被填滿。需要進行FLI移轉之前、請先變更原則並移除任何現有的Snapshot複本。可在移轉後再次設定Snapshot原則。

====
+
[NOTE]
====
LUN create命令會根據分割區偏移量來偵測大小和對齊方式、並使用Foreign磁碟選項來建立LUN。有關I/O不一致的審查、請參閱NetApp知識庫文章*什麼是不一致的I/O *？另請注意、有些I/O似乎總是部分寫入、因此看起來會不一致。例如資料庫記錄。

====
+
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/What_is_an_unaligned_I%2F%2FO%3F["什麼是未對齊的I/O？"]

. 建立目標LUN。「LUN create」命令會根據分割區偏移量來偵測大小和對齊方式、然後使用Foreign磁碟引數來建立LUN。
+
[listing]
----
cluster::*> lun create -vserver fli -path /vol/fli_vol/OnlineFLI_LUN -ostype windows_2008 -foreign-disk 600601603F103100662E70861000E511

Created a LUN of size 1t (1099511627776)
----
. 驗證新LUN。
+
[listing]
----
cluster::*> lun show -vserver fli
Vserver   Path                            State   Mapped   Type        Size
--------- ------------------------------- ------- -------- -------- --------
fli       /vol/fli_vol/OnlineFLI_LUN      online  unmapped windows_2008  1TB
----
. 使用主機啟動器建立傳輸協定FCP的群組。
+
[listing]
----
cluster::*> igroup create -vserver fli -igroup FLI -protocol fcp -ostype windows -initiator 10:00:00:00:c9:e6:e2:79
----
. 確認主機登入新igroup的所有路徑。
+
[listing]
----
cluster::*> igroup show –vserver fli –igroup FLI
   Vserver name: fli
    Igroup name: FLI
       Protocol: fcp
     OS Type: Windows
Portset Binding Igroup: -
   Igroup UUID: 5c664f48-0017-11e5-877f-00a0981cc318
          ALUA: true
    Initiators: 10:00:00:00:c9:e6:e2:77 (logged in)
10:00:00:00:c9:e6:e2:79 (logged in)
----
. 使目的地LUN離線。
+
[listing]
----
cluster::*> lun offline -vserver fli -path /vol/fli_vol/OnlineFLI_LUN

Warning: This command will take LUN "/vol/fli_vol/OnlineFLI_LUN" in Vserver "fli" offline.
Do you want to continue? {y|n}: y
----
. 將目的地LUN對應至igroup。
+
[listing]
----
cluster::*> lun map -vserver fli -path /vol/fli_vol/OnlineFLI_LUN -igroup FLI
----
. 在新LUN與外部LUN之間建立匯入關係。
+
[listing]
----
cluster::*> lun import create -vserver fli -path /vol/fli_vol/OnlineFLI_LUN -foreign-disk 600601603F103100662E70861000E511
----

