---
permalink: san-migration/task_fli_offline_verifying_migration_results.html 
sidebar: sidebar 
keywords: fli offline, verify, migration, results 
summary: 驗證工作是選用的、但建議使用。這是來源LUN與目的地LUN的區塊間比較。驗證工作所需時間幾乎與移轉時間相同或稍微長一點。 
---
= FLI離線：驗證移轉結果
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
驗證工作是選用的、但建議使用。這是來源LUN與目的地LUN的區塊間比較。驗證工作所需時間幾乎與移轉時間相同或稍微長一點。

.步驟
. 啟動驗證工作以比較來源和目的地LUN。監控驗證進度。
+
[listing]
----
DataMig-cmode::*> lun import verify start -vserver datamig -path /vol/winvol/bootlun

DataMig-cmode::*> lun import verify start -vserver datamig -path /vol/winvol/fdrive

DataMig-cmode::*> lun import verify start -vserver datamig -path /vol/winvol/gdrive
----
. 監控確認工作狀態。
+
[listing]
----
DataMig-cmode::*> lun import show -vserver datamig -fields vserver, foreign-disk, path, admin-state, operational-state, percent-complete, imported-blocks, total-blocks, , estimated-remaining-duration
vserver foreign-disk path               admin-state operational-state percent-complete imported-blocks total-blocks estimated-remaining-duration
------- ------------ ------------------ ----------- ----------------- ---------------- --------------- ------------ ----------------------------
datamig 83017542000E /vol/winvol/fdrive started     in_progress       57               -               4194304      00:01:19
datamig 83017542000F /vol/winvol/gdrive started     in_progress       40               -               6291456      00:02:44
datamig 830175420010 /vol/linuxvol/bootlun
                                        started     in_progress       8                -               41943040     00:20:29
3 entries were displayed.
----
. 確認工作已完成。
+
[listing]
----
DataMig-cmode::*> lun import show -vserver datamig -fields vserver, foreign-disk, path, admin-state, operational-state, percent-complete, imported-blocks, total-blocks, , estimated-remaining-duration
vserver foreign-disk path               admin-state operational-state percent-complete imported-blocks total-blocks estimated-remaining-duration
------- ------------ ------------------ ----------- ----------------- ---------------- --------------- ------------ ----------------------------
datamig 83017542000E /vol/winvol/fdrive started     completed         100              -               4194304      -
datamig 83017542000F /vol/winvol/gdrive started     completed         100              -               6291456      -
datamig 830175420010 /vol/linuxvol/bootlun
                                        started     completed         100              -               41943040     -
3 entries were displayed.
----
. 驗證完成後、請停止驗證工作。
+
[listing]
----
DataMig-cmode::*> lun import verify stop -vserver datamig -path /vol/esxvol/winrdmplun
----
. 刪除匯入關係以移除移轉工作。
+
[listing]
----
DataMig-cmode::*> lun import delete -vserver datamig -path /vol/winvol/bootlun

DataMig-cmode::*> lun import delete -vserver datamig -path /vol/winvol/fdrive

DataMig-cmode::*> lun import delete -vserver datamig -path /vol/winvol/gdrive
----
. 確認匯入工作已刪除。
+
[listing]
----
DataMig-cmode::*> lun import show -vserver datamig
There are no entries matching your query.
----
. 將Foreign LUN（外部LUN）屬性標記為「假」。
+
[listing]
----

DataMig-cmode::*> storage disk modify { -serial-number 83017542001E }
-is-foreign false

DataMig-cmode::*> storage disk modify { -serial-number 83017542000E }
-is-foreign false

DataMig-cmode::*> storage disk modify { -serial-number 83017542000F }
-is-foreign false
----
. 驗證外部LUN在匯入後是否標記為「假」。
+
[listing]
----
DataMig-cmode::*> storage disk show -array-name HITACHI_DF600F_1 -fields disk, serial-number, container-type, owner,import-in-progress, is-foreign
disk     owner is-foreign container-type import-in-progress serial-number
-------- ----- ---------- -------------- ------------------ -------------
HIT-1.2  -     false      unassigned     false              83017542001E
HIT-1.3  -     false      unassigned     false              83017542000E
HIT-1.4  -     false      unassigned     false              83017542000F
3 entries were displayed.
----
. 使用LUN online命令使目的地LUN聯機。
+
[listing]
----
DataMig-cmode::*> lun online -vserver datamig -path /vol/winvol/bootlun

DataMig-cmode::*> lun online -vserver datamig -path /vol/winvol/fdrive

DataMig-cmode::*> lun online -vserver datamig -path /vol/winvol/gdrive
----
. 驗證LUN是否在線上。
+
[listing]
----
DataMig-cmode::*> lun show -vserver datamig
Vserver   Path                            State   Mapped   Type        Size
--------- ------------------------------- ------- -------- -------- --------
datamig   /vol/esxvol/bootlun             online  mapped   vmware       20GB
datamig   /vol/esxvol/linuxrdmvlun        online  mapped   linux         2GB
datamig   /vol/esxvol/solrdmplun          online  mapped   solaris       2GB
3 entries were displayed.
----
+
[NOTE]
====
匯入記錄會儲存在叢集事件記錄檔中。

====
+
[listing]
----
  DataMig-cmode::*> event log  show –event fli*
  7/7/2014 18:37:21   DataMig-cmode-01 INFORMATIONAL fli.lun.verify.complete: Import verify of foreign LUN 83017542001E of size 42949672960 bytes from array model DF600F belonging to vendor HITACHI  with NetApp LUN QvChd+EUXoiS is successfully completed.
  7/7/2014 18:37:15   DataMig-cmode-01 INFORMATIONAL fli.lun.verify.complete: Import verify of foreign LUN 830175420015 of size 42949672960 bytes from array model DF600F belonging to vendor HITACHI  with NetApp LUN QvChd+EUXoiX is successfully completed.
  7/7/2014 18:02:21   DataMig-cmode-01 INFORMATIONAL fli.lun.import.complete: Import of foreign LUN 83017542000F of size 3221225472 bytes from array model DF600F belonging to vendor HITACHI  is successfully completed. Destination NetApp LUN is QvChd+EUXoiU.
----

